# docker-stack.yml - production (Docker Swarm)
# Use `docker stack deploy -c docker-stack.yml openfn` after initializing the swarm.
services:
services:

  postgres:
    image: postgres:13-alpine
    env_file: .env
    configs: []
    secrets:
      - postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  redis:
    image: redis:6-alpine
    networks:
      - backend
    deploy:
      replicas: 1

  lightning:
    image: ghcr.io/openfn/lightning:latest
    env_file: .env
    secrets:
      - app_secret
      - postgres_password
    networks:
      - backend
    ports:
      - "8070:80"
    # Traefik labels and proxy network removed: use host-level TLS (Nginx) to route to this service on port 8070
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

  devtools:
    image: ghcr.io/openfn/devtools:latest
    env_file: .env
    secrets:
      - app_secret
      - postgres_password
    networks:
      - backend
    # Traefik labels and proxy network removed: host Nginx should handle TLS and routing
    deploy:
      replicas: 1

  worker:
    image: ghcr.io/openfn/worker:latest
    env_file: .env
    secrets:
      - app_secret
      - postgres_password
    networks:
      - backend
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

volumes:
  pgdata:
  # traefik_letsencrypt: (removed - TLS handled by host Nginx/certbot)

networks:
  backend:
    external: false

secrets:
  postgres_password:
    external: true
  app_secret:
    external: true

# Notes:
# - Create Docker secrets before `docker stack deploy`:
#   docker secret create postgres_password ./secrets/postgres_password.txt
#   docker secret create app_secret ./secrets/app_secret.txt
# - The stack uses replicas and deploy settings which only apply in Swarm mode.
